###
#   Spring setting
###
spring:
  datasource:
    url: jdbc:h2:mem:bmwdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true
  servlet:
     multipart:
        max-file-size: 5MB
        max-request-size: 20MB
###
#   H2 Settings
#   http://localhost:8080/console
###
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
